"""Initial migration

Revision ID: a547cc88a45f
Revises: d109221df2d5
Create Date: 2025-02-19 11:07:45.311866

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a547cc88a45f'
down_revision = 'd109221df2d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    op.add_column('quotes', sa.Column('quote_amount', sa.Float(), nullable=False))
    op.add_column('quotes', sa.Column('details', sa.Text(), nullable=True))
    op.add_column('quotes', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('quotes', 'price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotes', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('quotes', 'updated_at')
    op.drop_column('quotes', 'details')
    op.drop_column('quotes', 'quote_amount')
    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_notifications_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='notifications_pkey')
    )
    # ### end Alembic commands ###
